# Generated by Django 3.0.5 on 2020-05-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.CharField(default='', max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
