# Generated by Django 3.0.5 on 2020-05-11 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='password',
        ),
    ]
