# Generated by Django 3.0.5 on 2020-05-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_notes_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='note_cross',
            field=models.BooleanField(default=False),
        ),
    ]
