# Generated by Django 3.0.5 on 2020-05-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_notes_note_cross'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='note_saved',
            field=models.BooleanField(default=True),
        ),
    ]
